// ─── All shared constants used across the app ───────────

export const DEPARTMENTS = [
  "All Company",
  "EMS",
  "Sales",
  "HR",
  "IT",
  "Operations",
  "Admin",
  "Marketing",
  "Finance",
  "Legal",
];

export const CATEGORIES_RECURRING = [
  "Subscriptions",
  "Iqama",
  "Service",
  "Utility",
  "Insurance",
  "Other",
];

export const CATEGORIES_ONETIME = [
  "Medical",
  "Equipment",
  "Events",
  "Legal",
  "Training",
  "Maintenance",
  "Vendor Payment",
  "Other",
];

export const SAR_RATES = { SAR: 1, USD: 3.75, KWD: 12.2, EUR: 4.05 };

export const ROLE_CONFIG = {
  staff: {
    label: "Staff",
    color: "#6B7A99",
    desc: "Submit requests only",
    pages: ["recurring", "onetime", "entitlements"],
    canApprove: [],
    canSubmit: true,
    canPay: false,
    canViewAll: false,
  },
  manager: {
    label: "Manager",
    color: "#F97316",
    desc: "Approve Level 1 — sees own submissions + pending queue",
    pages: ["dashboard", "forecast", "onetime", "entitlements", "recurring", "approvals"],
    canApprove: ["pending_manager", "pending_approval"],
    canSubmit: true,
    canPay: false,
    canViewAll: false,
  },
  vp: {
    label: "VP",
    color: "#14B8A6",
    desc: "Approve Entitlements Level 2",
    pages: ["dashboard", "forecast", "onetime", "entitlements", "recurring", "approvals"],
    canApprove: ["pending_vp"],
    canSubmit: true,
    canPay: false,
    canViewAll: false,
  },
  hr: {
    label: "HR",
    color: "#A78BFA",
    desc: "Approve Entitlements Level 3",
    pages: ["dashboard", "forecast", "onetime", "entitlements", "recurring", "approvals"],
    canApprove: ["pending_hr"],
    canSubmit: true,
    canPay: false,
    canViewAll: false,
  },
  ceo: {
    label: "CEO",
    color: "#EC4899",
    desc: "Review & Release — sees pending CEO queues",
    pages: ["dashboard", "forecast", "onetime", "entitlements", "recurring", "approvals"],
    canApprove: [
      "pending_ceo_1",
      "pending_ceo_2",
      "pending_ceo_1_rec",
      "pending_ceo_2_rec",
      "pending_schedule_ceo",
    ],
    canSubmit: false,
    canPay: false,
    canViewAll: false,
  },
  finance: {
    label: "Finance",
    color: "#F59E0B",
    desc: "Full access — all requests, payments, approvals",
    pages: ["dashboard", "forecast", "recurring", "onetime", "entitlements", "approvals", "analytics", "reports"],
    canApprove: [
      "pending_finance",
      "pending_finance_rec",
      "pending_pay",
      "pending_pay_rec",
      "pending_schedule_finance",
    ],
    canSubmit: true,
    canPay: true,
    canViewAll: true,
  },
  executive: {
    label: "Executive",
    color: "#8B5CF6",
    desc: "Read-only full overview",
    pages: ["dashboard", "forecast", "recurring", "onetime", "entitlements", "approvals", "analytics", "reports", "permissions"],
    canApprove: [],
    canSubmit: false,
    canPay: false,
    canViewAll: true,
  },
  admin: {
    label: "Admin",
    color: "#EF4444",
    desc: "Full system access — all pages, all permissions",
    pages: ["dashboard", "forecast", "recurring", "onetime", "entitlements", "approvals", "analytics", "reports", "audit", "notifications", "permissions", "departments"],
    canApprove: [
      "pending_manager",
      "pending_approval",
      "pending_vp",
      "pending_hr",
      "pending_ceo_1",
      "pending_ceo_2",
      "pending_ceo_1_rec",
      "pending_ceo_2_rec",
      "pending_finance",
      "pending_finance_rec",
      "pending_pay",
      "pending_pay_rec",
      "pending_schedule_finance",
      "pending_schedule_ceo",
    ],
    canSubmit: true,
    canPay: true,
    canViewAll: true,
  },
};

export const ALL_NAV = [
  { id: "dashboard", label: "Dashboard", icon: "◼", section: "main" },
  { id: "forecast", label: "Forecast", icon: "📈", section: "main" },
  { id: "recurring", label: "Recurring", icon: "↻", section: "main" },
  { id: "onetime", label: "One-Time", icon: "≡", section: "main" },
  { id: "entitlements", label: "Entitlements", icon: "👤", section: "main" },
  { id: "approvals", label: "Approvals", icon: "✓", section: "main" },
  { id: "analytics", label: "Analytics", icon: "📊", section: "insights" },
  { id: "reports", label: "Reports", icon: "⬇", section: "insights" },
  { id: "audit", label: "Audit Log", icon: "🗒", section: "admin" },
  { id: "notifications", label: "Notifications", icon: "🔔", section: "admin" },
  { id: "permissions", label: "Permissions", icon: "🔑", section: "admin" },
  { id: "departments", label: "Departments", icon: "🏢", section: "admin" },
];

export const DEFAULT_PERMISSIONS = {
  staff: {
    pages: ["recurring", "onetime", "entitlements"],
    canSubmit: true,
    canApproveL1: false,
    canApproveVP: false,
    canApproveHR: false,
    canApproveCEO: false,
    canApproveFinance: false,
    canPay: false,
    canViewAll: false,
    canExport: false,
    canManageUsers: false,
  },
  manager: {
    pages: ["dashboard", "forecast", "onetime", "entitlements", "recurring", "approvals"],
    canSubmit: true,
    canApproveL1: true,
    canApproveVP: false,
    canApproveHR: false,
    canApproveCEO: false,
    canApproveFinance: false,
    canPay: false,
    canViewAll: false,
    canExport: false,
    canManageUsers: false,
  },
  vp: {
    pages: ["dashboard", "forecast", "onetime", "entitlements", "recurring", "approvals"],
    canSubmit: true,
    canApproveL1: false,
    canApproveVP: true,
    canApproveHR: false,
    canApproveCEO: false,
    canApproveFinance: false,
    canPay: false,
    canViewAll: false,
    canExport: false,
    canManageUsers: false,
  },
  hr: {
    pages: ["dashboard", "forecast", "onetime", "entitlements", "recurring", "approvals"],
    canSubmit: true,
    canApproveL1: false,
    canApproveVP: false,
    canApproveHR: true,
    canApproveCEO: false,
    canApproveFinance: false,
    canPay: false,
    canViewAll: false,
    canExport: false,
    canManageUsers: false,
  },
  ceo: {
    pages: ["dashboard", "forecast", "onetime", "entitlements", "recurring", "approvals"],
    canSubmit: false,
    canApproveL1: false,
    canApproveVP: false,
    canApproveHR: false,
    canApproveCEO: true,
    canApproveFinance: false,
    canPay: false,
    canViewAll: false,
    canExport: true,
    canManageUsers: false,
  },
  finance: {
    pages: ["dashboard", "forecast", "recurring", "onetime", "entitlements", "approvals", "analytics", "reports"],
    canSubmit: true,
    canApproveL1: false,
    canApproveVP: false,
    canApproveHR: false,
    canApproveCEO: false,
    canApproveFinance: true,
    canPay: true,
    canViewAll: true,
    canExport: true,
    canManageUsers: false,
  },
  executive: {
    pages: ["dashboard", "forecast", "recurring", "onetime", "entitlements", "approvals", "analytics", "reports", "permissions"],
    canSubmit: false,
    canApproveL1: false,
    canApproveVP: false,
    canApproveHR: false,
    canApproveCEO: false,
    canApproveFinance: false,
    canPay: false,
    canViewAll: true,
    canExport: true,
    canManageUsers: true,
  },
  admin: {
    pages: ["dashboard", "forecast", "recurring", "onetime", "entitlements", "approvals", "analytics", "reports", "audit", "notifications", "permissions", "departments"],
    canSubmit: true,
    canApproveL1: true,
    canApproveVP: true,
    canApproveHR: true,
    canApproveCEO: true,
    canApproveFinance: true,
    canPay: true,
    canViewAll: true,
    canExport: true,
    canManageUsers: true,
  },
};

export const C = {
  bg: "#0B0F1A",
  surface: "#131929",
  card: "#1A2236",
  border: "#253047",
  accent: "#3B82F6",
  accentGlow: "#3B82F620",
  gold: "#F59E0B",
  green: "#10B981",
  red: "#EF4444",
  orange: "#F97316",
  text: "#E8EDF5",
  muted: "#6B7A99",
  subtle: "#2A3655",
  purple: "#8B5CF6",
};

export const statusConfig = {
  upcoming: { label: "Upcoming", color: "#3B82F6" },
  overdue: { label: "Overdue", color: "#EF4444" },
  paid: { label: "Paid", color: "#10B981" },

  pending_approval: { label: "Pending Approval", color: "#F97316" },
  pending_manager: { label: "Pending Manager", color: "#F97316" },
  pending_ceo_1: { label: "Pending CEO", color: "#EC4899" },
  pending_finance: { label: "Pending Finance", color: "#F59E0B" },
  pending_ceo_2: { label: "Pending CEO – Release", color: "#EC4899" },

  // Updated One-Time schedule flow
  pending_schedule_finance: { label: "Finance Schedule", color: "#8B5CF6" },
  pending_schedule_ceo: { label: "CEO Schedule Approval", color: "#C026D3" },
  pending_bank: { label: "Bank Release", color: "#3B82F6" },
  pending_receipt: { label: "Upload Receipt", color: "#10B981" },
  pending_invoice: { label: "Upload Invoice", color: "#14B8A6" },

  approved: { label: "Awaiting Payment", color: "#8B5CF6" },
  pending_pay: { label: "Pay & Docs", color: "#8B5CF6" },
  paid_onetime: { label: "Paid", color: "#10B981" },
  rejected: { label: "Rejected", color: "#EF4444" },

  pending_vp: { label: "Pending VP", color: "#14B8A6" },
  pending_hr: { label: "Pending HR", color: "#A78BFA" },

  pending_pay_rec: { label: "Pay & Docs", color: "#8B5CF6" },
  pending_ceo_1_rec: { label: "Pending CEO", color: "#EC4899" },
  pending_ceo_2_rec: { label: "Pending CEO – Release", color: "#EC4899" },
  pending_finance_rec: { label: "Pending Finance", color: "#F59E0B" },
};

export const priorityConfig = {
  high: { label: "High", color: "#EF4444" },
  medium: { label: "Medium", color: "#F59E0B" },
  low: { label: "Low", color: "#10B981" },
};

export const GENERAL_STEPS = [
  { key: "pending_manager", label: "Manager", color: "#F97316" },
  { key: "pending_ceo_1", label: "CEO Approval", color: "#EC4899" },
  { key: "pending_finance", label: "Finance Approval", color: "#F59E0B" },
  { key: "pending_schedule_finance", label: "Finance Schedule", color: "#8B5CF6" },
  { key: "pending_schedule_ceo", label: "CEO Schedule", color: "#C026D3" },
  { key: "pending_bank", label: "Bank Release", color: "#3B82F6" },
  { key: "pending_receipt", label: "Upload Receipt", color: "#10B981" },
  { key: "pending_invoice", label: "Employee Invoice", color: "#14B8A6" },
  { key: "paid_onetime", label: "Paid", color: "#10B981" },
];

export const ENTITLEMENT_STEPS = [
  { key: "pending_manager", label: "Manager" },
  { key: "pending_vp", label: "VP" },
  { key: "pending_hr", label: "HR" },
  { key: "pending_ceo_1", label: "CEO Review" },
  { key: "pending_finance", label: "Finance" },
  { key: "pending_ceo_2", label: "CEO Release" },
  { key: "pending_pay", label: "Pay & Docs" },
  { key: "paid_onetime", label: "Paid" },
];

export const RECURRING_STEPS = [
  { key: "pending_approval", label: "Manager" },
  { key: "pending_ceo_1_rec", label: "CEO Review" },
  { key: "pending_finance_rec", label: "Finance" },
  { key: "pending_ceo_2_rec", label: "CEO Release" },
  { key: "pending_pay_rec", label: "Pay & Docs" },
  { key: "paid", label: "Paid" },
];

export const ALL_PAGES = [
  { id: "dashboard", label: "Dashboard", icon: "◼", section: "MAIN" },
  { id: "forecast", label: "Forecast", icon: "📈", section: "MAIN" },
  { id: "recurring", label: "Recurring", icon: "↻", section: "MAIN" },
  { id: "onetime", label: "One-Time", icon: "≡", section: "MAIN" },
  { id: "entitlements", label: "Entitlements", icon: "👤", section: "MAIN" },
  { id: "approvals", label: "Approvals", icon: "✓", section: "MAIN" },
  { id: "analytics", label: "Analytics", icon: "📊", section: "INSIGHTS" },
  { id: "reports", label: "Reports", icon: "⬇", section: "INSIGHTS" },
  { id: "audit", label: "Audit Log", icon: "🗒", section: "ADMIN" },
  { id: "notifications", label: "Notifications", icon: "🔔", section: "ADMIN" },
  { id: "permissions", label: "Permissions", icon: "🔑", section: "ADMIN" },
  { id: "departments", label: "Departments", icon: "🏢", section: "ADMIN" },
];

export const ALL_PAGE_IDS = ALL_PAGES.map((p) => p.id);

export const PERM_LABELS = {
  canSubmit: {
    label: "Submit Requests",
    icon: "📤",
    desc: "Create new one-time, entitlement, and recurring requests",
  },
  canApproveL1: {
    label: "Approve L1 (Mgr)",
    icon: "✓",
    desc: "Approve Level 1 in all three queues",
  },
  canApproveVP: {
    label: "Approve VP",
    icon: "✓",
    desc: "Approve entitlement VP level",
  },
  canApproveHR: {
    label: "Approve HR",
    icon: "✓",
    desc: "Approve entitlement HR level",
  },
  canApproveCEO: {
    label: "Approve CEO",
    icon: "✓",
    desc: "CEO review & release approvals",
  },
  canApproveFinance: {
    label: "Approve Finance",
    icon: "✓",
    desc: "Finance-level approvals",
  },
  canPay: {
    label: "Record Payments",
    icon: "💳",
    desc: "Record payment details and upload receipts",
  },
  canViewAll: {
    label: "View All Data",
    icon: "👁",
    desc: "See all users' submissions (not just own)",
  },
  canExport: {
    label: "Export Reports",
    icon: "⬇",
    desc: "Download financial reports",
  },
  canManageUsers: {
    label: "Manage Permissions",
    icon: "🔑",
    desc: "Change role permissions and user assignments",
  },
};